import './globals.css'
import { Poppins } from "next/font/google";

const poppins = Poppins({ 
  weight: ["400", "700"],
  subsets: ['latin'] })

export const metadata = {
  title: 'Arvist',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
